nelmio_api_doc:
    documentation:
        servers:
            - url: http://api.example.com/unsafe
              description: API over HTTP
            - url: https://api.example.com/secured
              description: API over HTTPS
        info:
            title: BileMo
            description: Rest API
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
        host_patterns:
            - ^api\.